'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { defaults, resolve } = require('../lib/renderPreferences');
const { buildPlanGroundedPrompt, buildStyleDescription, describeLevelEdges } = require('../api/render');
const { renderPlanSvg } = require('../lib/renderPlanSvg');
const { renderedFloorFill } = require('../lib/renderedPlanStyles');

test('render site defaults follow every floor-plan lot choice, with explicit values winning', () => {
  for (const [lot, density] of [
    ['Suburban standard lot', 'Detached neighboring homes'], ['Suburban corner lot', 'Detached neighboring homes'],
    ['Urban tight lot', 'Close urban neighbors'], ['Rural acreage', 'Open rural edge'],
    ['View focused site', 'View-oriented sparse context'], ['Waterfront lot', 'View-oriented sparse context'],
  ]) {
    const d = defaults({ lotContext: lot, garage: 'None' });
    assert.equal(d.lotContext, lot); assert.equal(d.contextDensity, density);
    assert.equal(d.drivewayStyle, 'Minimal hardscape');
  }
  assert.equal(defaults({ location: '78701' }).zipCode, '78701');
  assert.equal(defaults({ location: 'Austin' }).zipCode, '');
  assert.equal(defaults({ lotContext: 'Rural acreage', topography: 'Gentle rear slope' }).topography, 'Gentle rear slope');
});

test('all style families and custom finishes seed render defaults', () => {
  for (const [style, siding, roof] of [
    ['Craftsman (Wood & Stone)', 'Cedar lap', 'Architectural asphalt'],
    ['Modern Farmhouse (Board & Batten)', 'Board & batten', 'Standing seam metal'],
    ['Traditional Colonial (Brick)', 'Brick', 'Architectural asphalt'],
    ['Contemporary Modern (Concrete)', 'Concrete panel', 'Flat membrane'],
    ['Mediterranean (Stucco & Tile)', 'Stucco', 'Clay tile'],
  ]) {
    const d = defaults({ materials: style });
    assert.equal(d.exteriorSiding, siding); assert.equal(d.roofMaterial, roof);
  }
  assert.equal(defaults({ finishOverrides: { exteriorSiding: 'Stone' } }).exteriorSiding, 'Stone');
  assert.equal(defaults({ materials: 'Modern Farmhouse (Board & Batten)' }, { finishSpec: { styleLabel: 'Craftsman (Wood & Stone)', exterior: { primaryCladding: { label: 'Cedar lap' } } } }).exteriorSiding, 'Board & batten');
  assert.match(buildStyleDescription('Modern Farmhouse (Board & Batten)', ''), /farmhouse/);
  assert.match(buildStyleDescription('Craftsman (Wood & Stone)', ''), /craftsman/);
});

test('intentional overrides survive updated survey; inherited fields refresh; legacy defaults migrate', () => {
  const saved = { version: 2, overrides: { timeOfDay: 'Night', landscaping: 'Minimal / gravel' } };
  const next = resolve({ lotContext: 'Rural acreage', finishOverrides: { exteriorSiding: 'Brick' } }, saved);
  assert.equal(next.timeOfDay, 'Night'); assert.equal(next.landscaping, 'Minimal / gravel');
  assert.equal(next.contextDensity, 'Open rural edge'); assert.equal(next.exteriorSiding, 'Brick');
  assert.equal(resolve({ lotContext: 'Rural acreage' }, { contextDensity: 'Detached neighboring homes' }).contextDensity, 'Open rural edge');
  assert.equal(resolve({}, { version: 2, overrides: { weather: '', stories: '10 Stories' } }).weather, '');
  assert.equal(resolve({}, saved).stories, undefined);
  assert.equal(resolve({}, null).timeOfDay, 'Midday');
});

test('browser and backend share the same preference implementation', () => {
  const normalized = file => fs.readFileSync(path.join(__dirname, file), 'utf8').replace(/\r\n/g, '\n');
  const generated = normalized('../../frontend-keystone/src/lib/renderPreferences.generated.js');
  const expected = '// GENERATED by scripts/prebuild.mjs from backend-keystone/lib/renderPreferences.js.\n'
    + '// Do not edit. Edit the conversion backend and re-run the build.\n'
    + normalized('../lib/renderPreferences.js')
    + '\nexport default globalThis.KeystoneRenderPreferences;\n';
  assert.equal(generated, expected);
});

const plan = { levels: [{ level: 1, width: 24, height: 24,
  rooms: [{ id: 'garage', type: 'garage', label: 'Garage', x: 0, y: 0, w: 12, h: 24 },
    { id: 'entry', type: 'entry', label: 'Entry', x: 12, y: 0, w: 12, h: 24 }],
  doors: [{ a: 'garage', b: '__exterior__', x: 6, y: 24, dir: 'horizontal', width: 9, garageDoor: true },
    { a: 'entry', b: '__exterior__', x: 18, y: 24, dir: 'horizontal', width: 4, isMainEntry: true }],
  windows: [{ roomId: 'entry', x: 18, y: 0, width: 6, dir: 'horizontal' }],
  furniture: [{ roomId: 'entry', kind: 'bench', x: 14, y: 4, w: 4, h: 2 }],
}] };

test('3D prompt uses actual stories, opening schedule and entry/garage door side', () => {
  const prompt = buildPlanGroundedPrompt({ surveyData: { stories: '2 Stories', frontFacing: 'South', garage: 'None', materials: 'Craftsman (Wood & Stone)' },
    renderSurveyData: { version: 2, overrides: { exteriorSiding: 'Brick', timeOfDay: 'Night' } }, planSpec: plan });
  assert.match(prompt, /Program summary: 1 stories/);
  assert.match(prompt, /garage side front\/bottom, entry side front\/bottom/);
  assert.match(prompt, /garage door at \(6,24\)ft, horizontal, width 9ft/);
  assert.match(prompt, /window at \(18,0\)ft, horizontal, width 6ft/);
  assert.match(prompt, /Primary cladding: Brick/); assert.match(prompt, /night scene/);
  assert.match(prompt, /Architectural style family: Craftsman/);
  assert.match(prompt, /Site context: well-kept suburban lot/);
  assert.doesNotMatch(prompt, /larger glazing where appropriate/);
  for (const [facing, edge] of [['North', 'top'], ['South', 'bottom'], ['East', 'right'], ['West', 'left']]) {
    assert.match(describeLevelEdges(plan.levels[0], facing), new RegExp(`front/${edge}:`));
  }
});

test('normal and rendered views preserve plan geometry, door sizes and glazing', () => {
  const before = structuredClone(plan);
  for (const style of ['normal', 'rendered']) {
    const svg = renderPlanSvg(plan, { style });
    assert.match(svg, /A 72 72 /);
    assert.match(svg, /width="108" height="8"/);
    assert.match(svg, /class="exterior-outline"/);
    assert.match(svg, /viewBox="0 0 632 712"/);
    if (style === 'rendered') assert.match(svg, /ksRender_wallShadow/);
    else assert.doesNotMatch(svg, /ksRender_wallShadow/);
  }
  assert.deepEqual(plan, before);
  assert.equal(renderedFloorFill({ type: 'living_room' }, { interiorFinishes: { flooring: { public: { material: 'polished_concrete' } } } }), 'url(#ksRender_concrete)');
  assert.equal(renderedFloorFill({ type: 'bathroom' }), 'url(#ksRender_tile)');
});

test('render lighting preserves the selected season and does not add sunlight to night', () => {
  const prompt = buildPlanGroundedPrompt({ surveyData: { frontFacing: 'South' }, planSpec: plan,
    renderSurveyData: { version: 2, overrides: { season: 'Winter (Snow)', timeOfDay: 'Night' } } });
  assert.match(prompt, /Winter \(Snow\) season/);
  assert.doesNotMatch(prompt, /bright southern light/);
  const cloudy = buildPlanGroundedPrompt({ surveyData: {}, planSpec: plan,
    renderSurveyData: { version: 2, overrides: { weather: 'Overcast sky', timeOfDay: 'Midday' } } });
  assert.match(cloudy, /diffuse daylight/); assert.doesNotMatch(cloudy, /crisp shadows/);
});
