'use strict';

const STAGE_ORDER = Object.freeze([
  'site_bounds',
  'main_entrance',
  'common_core',
  'stair_core',
  'circulation_loop',
  'private_extremities',
  'buffer_nodes',
  'detailing_nodes',
]);

const NODE_TYPE_METADATA = Object.freeze({
  entrance_room: {
    stage: 'main_entrance',
    privacyDepth: 0,
    privacyLevel: 'public',
    exteriorEdgesRequired: 1,
    sunAffinity: ['south', 'front'],
    terminal: false,
  },
  common_area: {
    stage: 'common_core',
    privacyDepth: 1,
    privacyLevel: 'semi_public',
    exteriorEdgesRequired: 2,
    sunAffinity: ['south', 'west'],
    terminal: false,
  },
  farmhouse_kitchen: {
    stage: 'common_core',
    privacyDepth: 1,
    privacyLevel: 'semi_public',
    exteriorEdgesRequired: 1,
    sunAffinity: ['south', 'east', 'rear'],
    terminal: false,
  },
  dining_room: {
    stage: 'common_core',
    privacyDepth: 1,
    privacyLevel: 'semi_public',
    exteriorEdgesRequired: 1,
    sunAffinity: ['south', 'west'],
    terminal: false,
  },
  stair_core: {
    stage: 'stair_core',
    privacyDepth: 2,
    privacyLevel: 'circulation',
    exteriorEdgesRequired: 0,
    sunAffinity: [],
    terminal: false,
  },
  landing: {
    stage: 'circulation_loop',
    privacyDepth: 2,
    privacyLevel: 'circulation',
    exteriorEdgesRequired: 0,
    sunAffinity: ['borrowed_light'],
    terminal: false,
  },
  lower_landing: {
    stage: 'circulation_loop',
    privacyDepth: 1,
    privacyLevel: 'circulation',
    exteriorEdgesRequired: 0,
    sunAffinity: ['borrowed_light'],
    terminal: false,
  },
  primary_suite: {
    stage: 'private_extremities',
    privacyDepth: 4,
    privacyLevel: 'private',
    exteriorEdgesRequired: 2,
    sunAffinity: ['east', 'south'],
    terminal: true,
  },
  secondary_bedroom: {
    stage: 'private_extremities',
    privacyDepth: 3,
    privacyLevel: 'private',
    exteriorEdgesRequired: 1,
    sunAffinity: ['east'],
    terminal: true,
  },
  special_room: {
    stage: 'private_extremities',
    privacyDepth: 3,
    privacyLevel: 'private',
    exteriorEdgesRequired: 1,
    sunAffinity: ['east', 'north'],
    terminal: true,
  },
  library: {
    stage: 'private_extremities',
    privacyDepth: 3,
    privacyLevel: 'private',
    exteriorEdgesRequired: 2,
    sunAffinity: ['east', 'north'],
    terminal: true,
  },
  gym: {
    stage: 'private_extremities',
    privacyDepth: 2,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north', 'west'],
    terminal: true,
  },
  playroom: {
    stage: 'public_core',
    privacyDepth: 1,
    privacyLevel: 'semi_public',
    exteriorEdgesRequired: 1,
    sunAffinity: ['east', 'south'],
    terminal: true,
  },
  gaming_room: {
    stage: 'private_extremities',
    privacyDepth: 2,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 1,
    sunAffinity: ['north', 'east'],
    terminal: true,
  },
  movie_room: {
    stage: 'private_extremities',
    privacyDepth: 2,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: true,
  },
  music_room: {
    stage: 'private_extremities',
    privacyDepth: 3,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 1,
    sunAffinity: ['north', 'east'],
    terminal: true,
  },
  wine_cellar: {
    stage: 'buffer_nodes',
    privacyDepth: 2,
    privacyLevel: 'utility',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: true,
  },
  guest_bedroom: {
    stage: 'private_extremities',
    privacyDepth: 3,
    privacyLevel: 'private',
    exteriorEdgesRequired: 1,
    sunAffinity: ['east'],
    terminal: true,
  },
  study: {
    stage: 'private_extremities',
    privacyDepth: 3,
    privacyLevel: 'private',
    exteriorEdgesRequired: 1,
    sunAffinity: ['east', 'north'],
    terminal: true,
  },
  shared_bath: {
    stage: 'buffer_nodes',
    privacyDepth: 2,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: false,
  },
  secondary_private_bath: {
    stage: 'buffer_nodes',
    privacyDepth: 3,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: false,
  },
  lower_shared_bath: {
    stage: 'buffer_nodes',
    privacyDepth: 2,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: false,
  },
  primary_bath_buffer: {
    stage: 'buffer_nodes',
    privacyDepth: 3,
    privacyLevel: 'semi_private',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: false,
  },
  garage: {
    stage: 'buffer_nodes',
    privacyDepth: 1,
    privacyLevel: 'utility',
    exteriorEdgesRequired: 1,
    sunAffinity: ['north', 'west'],
    terminal: true,
  },
  mudroom: {
    stage: 'buffer_nodes',
    privacyDepth: 2,
    privacyLevel: 'utility',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: false,
  },
  laundry: {
    stage: 'buffer_nodes',
    privacyDepth: 2,
    privacyLevel: 'utility',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: false,
  },
  storage: {
    stage: 'buffer_nodes',
    privacyDepth: 2,
    privacyLevel: 'utility',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: true,
  },
  storage_upper: {
    stage: 'buffer_nodes',
    privacyDepth: 2,
    privacyLevel: 'utility',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: true,
  },
  suite_buffer: {
    stage: 'buffer_nodes',
    privacyDepth: 3,
    privacyLevel: 'utility',
    exteriorEdgesRequired: 0,
    sunAffinity: ['north'],
    terminal: false,
  },
});

function resolveSpecialRoomMetadata(type) {
  const normalized = String(type || '').trim().toLowerCase();
  return NODE_TYPE_METADATA[normalized] || null;
}

function nodeDefaults(role, overrides = {}) {
  const specialRoomMetadata = role === 'special_room'
    ? resolveSpecialRoomMetadata(overrides.type)
    : null;
  return {
    role,
    ...(NODE_TYPE_METADATA[role] || {}),
    ...(specialRoomMetadata || {}),
    ...overrides,
  };
}

module.exports = {
  NODE_TYPE_METADATA,
  STAGE_ORDER,
  nodeDefaults,
  resolveSpecialRoomMetadata,
};
