// Conversion-only shared preferences. Never invoke the legacy root generator:
// that generator writes into the existing frontend checkout.
import { readFileSync, writeFileSync } from 'node:fs';
import { assertConversion } from './conversion-config.mjs';

assertConversion(process.env);
const source = new URL('../../backend-keystone/lib/renderPreferences.js', import.meta.url);
const destination = new URL('../src/lib/renderPreferences.generated.js', import.meta.url);
const implementation = readFileSync(source, 'utf8').replace(/\r\n/g, '\n');
writeFileSync(destination,
  '// GENERATED by scripts/prebuild.mjs from backend-keystone/lib/renderPreferences.js.\n'
  + '// Do not edit. Edit the conversion backend and re-run the build.\n'
  + implementation + '\nexport default globalThis.KeystoneRenderPreferences;\n');
console.log('[keystone] conversion render preferences synced');
