"""Curated source-grounded rules. Rebuild rules.json and readable RULE-CATALOG.md."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
RULES=[]
def ref(source,number,section=False):
    return {'source_id':source,'locator':f'{"section" if section else "page"}-{number:04d}'}
def j(n): return ref('vastu-jain',n,True)
def p(): return ref('vastu-pathi',8,True)
def s(n): return ref('vastu-svoboda',n,True)
def c(n): return ref('vastu-chakrabarti',n)
def add(id,title,tier,tags,sources,principle,test,repair,conflict='',predicate=None,applies=None):
    RULES.append(dict(id=id,title=title,tier=tier,tags=tags.split(),sources=sources,
      principle=principle,measurement=test,repair=repair,conflict=conflict or 'No consensus claim; apply the selected household profile and mandatory safety constraints.',
      provenance='source_paraphrase_with_keystone_operationalization',
      review_status='curated_not_professionally_approved',predicate=predicate,applies_when=applies))
def pred(fact,op,value): return dict(fact=fact,op=op,value=value)
def optional(name): return pred(name+'.requested','eq',True)

# Tier zero is a feasibility gate; it is never traded for a better preference score.
add('G01','Confirm local adoption and municipal overlay',0,'jurisdiction coverage setback code',[ref('nbc206-2024',1),ref('nbc206-2024',5)],'Use applicable national provisions plus municipal rules; shared valley geography does not prove identical bylaws.','Record municipality, ward, rule versions and reviewer confirmation.','Resolve missing overlay before compliance claims.',predicate=pred('jurisdiction.reviewed','eq',True))
add('G02','Do not use draft commentary as the current seismic code',0,'seismic earthquake code',[ref('nbc105-commentary-draft',1),ref('nbc105-commentary-draft',2)],'The uploaded commentary labels itself a draft and discusses an older seismic code.','Current project design basis independently confirmed; draft excluded from automatic code thresholds.','Obtain applicable NBC 105 and engineer-approved analysis basis.',predicate=pred('structure.design_basis_reviewed','eq',True))
add('G03','Verify NBC 205 eligibility as a whole',0,'structure grid partial floor earthquake',[ref('nbc205-2024',15),ref('nbc205-2024',16),ref('nbc205-2024',17)],'Ready-to-use details depend on all scope and layout restrictions, not a single column-spacing check.','Review clauses 1.2, 4.1 and 4.2 including height, bays, projections, area and regularity.','Use individually engineered design when outside eligibility.',predicate=pred('structure.route_reviewed','eq',True))
add('G04','Represent nonstructural masonry correctly',0,'brick infill structure',[ref('nbc205-2024',15),ref('nbc205-2024',18)],'NBC 205 describes a frame without relying on masonry for vertical/seismic resistance; it also specifies brickwork. The title does not prohibit every brick wall.','Engineer decides actual infill interaction and loading model.','Revise model and calculations; never remove infill loads by a label.',predicate=pred('structure.infill_model_reviewed','eq',True))
add('G05','Preserve a verified structural load path',0,'structure columns beams grid',[ref('nbc205-2024',16),ref('nbc205-2024',17)],'The ready-to-use route requires vertical continuous lateral-load columns and restricts irregularity.','Check every member across levels and approved foundation/transfer conditions.','Move room/core arrangement, not unilaterally remove a column.',predicate=pred('structure.load_path_reviewed','eq',True))
add('G06','No Vaastu change may create unsafe geometry',0,'safety stairs door daylight',[ref('nbc206-2024',15),ref('nbc206-2024',16),ref('nbc206-2024',17),c(140)],'Mandatory spatial and safety conditions remain gates before Vaastu ranking.','Run adopted geometry/egress/structural/service checks after every preference repair.','Report conflicting requirements and propose a safe alternative.',predicate=pred('geometry.mandatory_checks_passed','eq',True))

# Source-checked architectural minima: profile applicability must be established first.
code_scope=pred('code.nbc206_2024_general_residential_confirmed','eq',True)
for id,title,page,clause,fact,op,value,unit in [
 ('C01','Residential stair minimum tread',15,'2.4.1 Table 4','stairs.minimum_tread_mm','gte',250,'mm'),
 ('C02','Residential stair maximum riser',15,'2.4.1 Table 4','stairs.maximum_riser_mm','lte',190,'mm'),
 ('C03','Maximum risers in each flight',15,'2.4.1 Table 4','stairs.maximum_flight_risers','lte',15,'risers'),
 ('C04','Stair clear headroom',15,'2.4.1 Table 4','stairs.minimum_headroom_mm','gte',2000,'mm'),
 ('C05','Habitable room height',16,'3.2.1','rooms.minimum_habitable_height_mm','gte',2400,'mm'),
 ('C06','Clearance below beams or false ceilings',16,'3.2.1','rooms.minimum_clear_height_below_obstruction_mm','gte',2100,'mm'),
 ('C07','Bathroom or WC height',16,'3.2.1','bathrooms.minimum_height_mm','gte',2000,'mm'),
 ('C08','Habitable room minimum dimension',16,'3.2.2 A','rooms.minimum_habitable_dimension_mm','gte',2000,'mm'),
 ('C09','Habitable room minimum area',16,'3.2.2 A','rooms.minimum_habitable_area_m2','gte',6,'m2'),
 ('C10','Kitchen minimum dimension',16,'3.2.2 B','kitchens.minimum_dimension_mm','gte',1800,'mm'),
 ('C11','Kitchen minimum area',16,'3.2.2 B','kitchens.minimum_area_m2','gte',5,'m2'),
]:
    add(id,title,0,'code residential '+('stairs' if fact.startswith('stairs') else 'room dimensions'),[ref('nbc206-2024',page)],f'Uploaded NBC 206:2024 {clause}: {op} {value} {unit}; confirm adopted scope before enforcement.',f'Use worst measured value across every applicable instance; {fact}. Flat/pitched roof and room classification exceptions require separate treatment.','Revise geometry and rerun all dependent validations. Minimum size alone does not prove furniture fit.',predicate=pred(fact,op,value),applies=code_scope)
add('C12','Exit width is occupancy-dependent',0,'stairs circulation code',[ref('nbc206-2024',13),ref('nbc206-2024',14)],'General residence minimum in Table 3 is 0.9m, but capacity, classification and effective occupant load also govern.','Implement full reviewed clause 2.4/Table 3 route; do not treat 900mm as universally sufficient.','Increase width or revise egress design; engineer/architect check.')
add('C13','Light and ventilation are separate tests',0,'daylight windows ventilation kitchen',[ref('nbc206-2024',17)],'Section 3.3 distinguishes daylight opening area, ventilation area, kitchens and climate region.','Check legal exposed openings, openable area and every room; inspect reference-example arithmetic before use.','Reposition rooms/openings or introduce a compliant court; no credit for blocked windows.')
add('C14','Internal daylight court is not a pipe shaft',0,'courtyard daylight shaft',[ref('nbc206-2024',17)],'Section 3.3 gives a 3m by 3m minimum internal court for natural light to habitable rooms in normal-rise buildings.','Verify normal-rise applicability, every court dimension and its open geometry; taller-building provisions require review.','Reserve a compliant court early or find another compliant daylight solution.')
add('C15','Limit naturally lit room depth',0,'daylight room depth',[ref('nbc206-2024',17)],'Section 3.3 excludes portions more than 7.5m from the relevant opening from being considered naturally lighted.','Evaluate the room polygon, not merely centroid distance.','Adjust room depth/openings; professional daylight review.')
add('C16','Confirm toilet type before applying dimensions',0,'toilet bathroom dimensions',[ref('nbc206-2024',16)],'Separate WC, bathroom and combined WC/bathroom have different minima in section 3.2.2.','Use source table: WC 0.9m/1.2m2; bath 1.2m/1.8m2; combined 1.2m/2.8m2, plus actual fixture clearances.','Resize or reclassify honestly; do not use WC-only area for a shower room.')
add('C17','Coordinate water and waste with maintenance access',0,'mep water drainage',[ref('nbc208-2003',1)],'Use the sanitary/plumbing source for project-specific provisions after adoption review, not a directional preference as engineering design.','Resolve pipe slopes, capacities, outfalls, hygiene/separation and service access with cited clauses.','Move routing or tank/core positions without violating engineering constraints.')

# Highest design-preference tier: room/house organization.
for id,title,pages,principle,measurement,repair in [
 ('B01','Separate FAR, coverage and usable area',[15,51,54],'FAR is counted floor area divided by plot area; coverage is counted ground footprint divided by plot area times 100. These are different accounts.','Maintain separate source-linked ledgers and explicit denominator; do not use carpet area as gross counted area.','Recompute each metric independently.'),
 ('B02','Make floor-area inclusions explicit',[15,52],'The glossary and FAR examples disagree on basements and balconies. Stair and parking exclusions also need applicable local confirmation.','Every spatial component has independent FAR and coverage inclusion decisions and source/reviewer evidence. Unknown decisions block a final total.','Resolve the local adopted definition; retain both conflicting references.'),
 ('B03','Coverage depends on plot size and occupancy',[54,55],'Resource section 1.2.4 lists residential/mixed residential coverage at 70% up to 250m2 and 60% above; this is a sourced candidate rule, not confirmed adoption for every municipality.','Test boundary 250m2 and occupancy; distinguish the separate model-bylaw table on next page.','Select reviewed local rule and all other constraints before generation.'),
 ('B04','Do not hardcode a valley-wide FAR',[51,52],'The resource illustrates KMC residential FAR 2.5 but also reproduces a model-bylaw residential value 1.75.','Track instrument, locality, use, road conditions and edition instead of selecting the more generous value.','Obtain the current applicable local FAR.'),
 ('B05','Parking exemption is metric-specific',[15,54],'The glossary excludes vehicle-parking/loading use from floor area. That does not establish a ground-coverage exemption for every roofed garage.','Classify open, roofed, enclosed, stilt and basement parking separately with FAR/coverage decisions.','Preserve actual plot use and access regardless of counting exemption.'),
 ('B06','Count actual partial-level geometry',[15,51],'Total floor area is accumulated over actual floors; a colloquial half-storey is not a fixed scalar.','Use each level polygon and use-specific exclusions, avoiding double-counted stairs/voids.','Recompute from versioned spatial components.'),
 ('B07','Apply setbacks and ROW independently of coverage',[16,56,57],'Coverage permission alone does not define a legal footprint. Resource distinguishes opening-side, blank-wall, road and height-related conditions.','Intersect actual site with applicable constraints and check projections; zero blank-wall setback is not a universal separation waiver.','Resolve adopted local conditions and engineered separation.'),
 ('B08','Treat height, FAR and light plane as simultaneous limits',[60],'Resource describes height controlled alongside FAR and light-plane provisions.','Evaluate actual levels/roof and local height definition; do not infer allowed storeys from FAR alone.','Revise program or level geometry.'),
 ('B09','Classify soil/engineering requirements before design route',[71,111,112,197],'Resource discusses building categories and investigation requirements; historical thresholds must be reconciled with current instruments.','Store project classification and professional interpretation; do not copy an inconsistent translated category into automatic eligibility.','Use reviewed current engineering route.'),
 ('B10','Permit workflow has staged technical and site checks',[125,126,127],'Resource separates designer submission, bylaw/code checks, field verification and staged permits.','Keep submitted, reviewed, approved and built/inspected states separate; use the municipality current procedure.','Do not call generated files a permit or assume a 30-day authority decision.'),
]:
    add(id,title,0,'area far coverage bylaw permit '+title.lower(),[ref('bylaws-resource-2023',n) for n in pages],principle,measurement,repair)

add('S01','Use the supplied 2025 seismic edition as the current reference',0,'seismic code earthquake',[ref('nbc105-2025',1),ref('nbc105-2025',2),ref('nbc105-2025',21)],'The new upload identifies NBC 105:2025, second revision. Keep older commentary separate and confirm project adoption.','Attach current source hash, engineer design basis and applicable revision; preserve older material for background only.','Replace obsolete code assumptions and re-review dependent engineering.')
add('S02','Resolve soil classification with site evidence and ward lookup',0,'soil municipality ward kathmandu seismic',[ref('nbc105-2025',44),ref('nbc105-2025',45),ref('nbc105-2025',46)],'Section 4.1.3 and Table 4-3 distinguish listed Kathmandu Valley wards and test-based soil classification.','Store municipality/ward plus site evidence. Nil in the table does not prove rock or low hazard.','Engineer confirms soil profile and table applicability; do not use one valley-wide soil constant.')
add('S03','Select seismic zoning from the applicable code route',0,'seismic zoning municipality earthquake',[ref('nbc105-2025',46)],'Section 4.1.4 refers to municipality values in Annex C and map interpolation.','Keep municipality identifiers and code provenance; source cross-reference numbering needs review before automating map lookup.','Use reviewed municipality/table value or reviewed location method; do not guess a national coefficient.')
add('S04','Check weak and soft storeys before accepting open parking',0,'parking soft storey structure seismic',[ref('nbc105-2025',55)],'Section 5.4.1 distinguishes strength and stiffness irregularities.','Store engineer-calculated strength/stiffness comparisons; geometry alone cannot prove either.','Revise lateral system and engineering when open ground floor conflicts with upper infill.')
add('S05','Review partial upper floors and offsets for irregularity',0,'partial floor setbacks structure seismic',[ref('nbc105-2025',55),ref('nbc105-2025',56),ref('nbc105-2025',57)],'Vertical geometry, mass, diaphragm and offset irregularities are separate checks.','Evaluate every full/partial level and stair/court void with engineering results.','Revise frame/layout; do not treat 3.5 as multiplication of a typical floor.')
add('S06','Do not confuse rectangular appearance with torsional adequacy',0,'torsion grid structure seismic',[ref('nbc105-2025',56)],'Section 5.4.2 evaluates displacement-based torsion and disallows extreme torsional irregularity.','Use structural analysis results, not only perimeter shape or Vaastu balance.','Engineer revises lateral configuration before architectural issue.')
add('S07','Design building separation from displacement requirements',0,'boundary separation seismic neighbor',[ref('nbc105-2025',58),ref('nbc105-2025',59)],'Section 5.5.2 addresses separation of independent units and clear gaps.','Engineer calculates relevant displacement/gap and evaluates adjoining site conditions; retain construction tolerances.','Reserve the required clear separation; observed flush neighbors do not justify ignoring the check.')
add('S08','Carry tanks, parapets and MEP into seismic coordination',0,'tank parapet mep anchorage seismic',[ref('nbc105-2025',71),ref('nbc105-2025',72),ref('nbc105-2025',74)],'Chapter 10 addresses nonstructural components, supports and connections.','Model weights, attachments and supported services; engineer determines applicable demands and anchorage.','Move/support/anchor components through reviewed engineering, even if a preferred direction changes.')
add('S09','Coordinate RC and masonry infill under the current design route',0,'rc masonry infill seismic',[ref('nbc105-2025',75)],'Annex A includes RC moment frames with unreinforced masonry infill among its covered systems.','Do not treat infill as architecturally invisible to seismic design; engineer selects provisions and detailing.','Resolve openings, frame interaction and member details before finalizing floor plans.')

add('V01','Fix north and the scope of every directional test',1,'north orientation geometry vastu',[s(14),c(132)],'Directional interpretation requires an explicit orientation and reference space.','Store north bearing and whether a rule refers to plot, building, floor, room or fixture; missing/uncertain north is unknown.','Ask for north confirmation before claiming Vaastu compliance.',predicate=pred('vastu.orientation_confirmed','eq',True))
add('V02','Prefer a coherent rectangular building domain',1,'plot shape rectangle vastu',[s(13),s(19),c(149)],'Square/rectangular spatial organization is preferred in these traditions.','Compare buildable polygon with candidate regular domains; never alter the actual surveyed parcel.','Fit a regular occupied volume inside lawful envelope; disclose losses/irregular exceptions.',predicate=pred('building.regular_domain','eq',True))
add('V03','Reserve a clear central Brahmasthana',1,'center courtyard brahmasthana vastu',[j(7),s(13),c(136),c(137)],'Keep the identified center spatially clear; traditions differ on exact size and open-to-sky treatment.','Explicit center polygon from selected grid; intersect with stairs, toilets and bulky obstructions. Courtyard versus usable open hall is a profile decision.','Shift core/wet rooms; do not remove load-bearing members or assume a tiny void passes daylight rules.',predicate=pred('vastu.center_clear','eq',True))
add('V04','Keep northeast light and uncluttered',1,'northeast daylight massing vastu',[j(9),p(),c(139)],'Prioritize openness and light in the northeast within legal site constraints.','Measure NE usable/open area and actual obstruction; separate visual openness from legal setbacks.','Move heavy storage and optional services away; retain required boundary protection.',predicate=pred('vastu.northeast_uncluttered','eq',True))
add('V05','Locate the puja space toward northeast',1,'puja prayer northeast vastu',[j(14),p(),c(140)],'NE is the selected first preference; Jain also allows N/E. Pathi allows different alternatives.','Classify puja polygon in the selected floor domain; record preferred versus fallback outcome.','Try NE first, then explicit profile alternatives.',conflict='Pathi allows W/S/NE; Jain prefers NE then N/E. Default uses NE; fallback requires recorded profile.',predicate=pred('puja.zone','eq','NE'),applies=optional('puja'))
add('V06','Separate puja from toilets in plan and section',1,'puja toilet adjacency stack vastu',[j(14),j(19),p()], 'Avoid puja next to, above/below or directly facing a toilet.','Check shared boundaries, door sightlines and vertical footprint overlaps; define adjacency tolerance in geometry adapter.','Move puja/toilet or insert a genuine separation; report unsatisfied conditions.',predicate=pred('puja.toilet_conflict','eq',False),applies=optional('puja'))
add('V07','No puja beneath or above a stair',1,'puja stairs stack vastu',[j(14)],'Jain discourages puja under or over stairs.','Intersect puja zone with full stair/landing envelope above and below.','Reposition puja as a dedicated suitable zone.',predicate=pred('puja.stair_overlap','eq',False),applies=optional('puja'))
add('V08','Place the kitchen in southeast first',1,'kitchen southeast northwest vastu',[j(16),p(),s(14),c(140)],'SE is a recurring kitchen preference; NW is an explicit alternative in Jain and Pathi.','Measure kitchen in building/floor domain separately from stove within kitchen.','Reserve SE during program allocation; use NW only as a reported alternative.',predicate=pred('kitchen.zone','eq','SE'))
add('V09','Avoid kitchen in northeast or southwest',1,'kitchen northeast southwest vastu',[j(16),p()], 'Protect NE from kitchen placement; these sources also discourage SW kitchen.','Evaluate every kitchen in multi-unit homes, not just ground floor.','Move wet/service cluster while preserving drainage and usable circulation.',predicate=pred('kitchens.all_avoid_ne_sw','eq',True))
add('V10','Place the primary bedroom southwest first',1,'bedroom primary southwest vastu',[j(18),p(),c(140)],'SW is the selected primary bedroom preference; Jain permits S/W alternatives.','Map requested primary suite and its actual floor; do not assign importance by gender/caste.','Try SW; explicitly report S/W fallback and any requested accessible-ground-floor conflict.',predicate=pred('primary_bedroom.zone','eq','SW'))
add('V11','Avoid primary bedroom in northeast or southeast',1,'bedroom primary northeast southeast vastu',[j(18)],'Jain discourages NE/SE primary sleeping spaces.','Check primary room zone independently of bed orientation.','Reallocate sleeping/private realm; do not fabricate medical consequences.',predicate=pred('primary_bedroom.zone','not_in',['NE','SE']))
add('V12','Prefer northwest or west toilets/bathrooms',1,'toilet bathroom northwest west vastu',[j(19),p()], 'Selected practical profile favors NW/W for wet toilet rooms.','Check each bathroom/WC room as a separate instance.','Group suitable wet rooms with legal light, vent and service routes.',conflict='Chakrabarti page 140 distinguishes bathroom E from toilet S. Do not merge that tradition silently with Jain.',predicate=pred('bathrooms.all_in_nw_w','eq',True))
add('V13','Avoid toilets in northeast and center',1,'toilet center northeast vastu',[j(19),p()], 'NE and center are excluded toilet zones in the selected profile.','Intersect full WC/wet room polygons with protected regions; a favorable centroid cannot excuse major overlap.','Move toilet core before furniture/finish optimization.',predicate=pred('bathrooms.avoid_ne_center','eq',True))
add('V14','Keep kitchen, puja and bathrooms out from under stairs',1,'stairs undercroft kitchen toilet puja vastu',[j(24),j(19)],'Storage is an allowed under-stair use in Jain; kitchen/bath/puja are discouraged.','Check room/stair envelopes in section and plan.','Use accessible storage only after headroom and safety checks.',predicate=pred('stairs.prohibited_undercroft_use','eq',False))
add('V15','Choose a documented stair-location tradition',1,'stairs south west northwest southeast vastu',[j(24),p()], 'Jain prefers S/W; Pathi prefers NW/SE. Both discourage NE.','Default profile selects Jain S/W family; save alternative consultant-approved profile rather than enforcing contradictory locations.','Reserve stair early with grid and daylight space.',conflict='Direct source conflict: S/W versus NW/SE. Default is an explicit Keystone selection, not consensus.',predicate=pred('stairs.selected_profile_location_satisfied','eq',True))
add('V16','Keep stair out of northeast and center',1,'stairs northeast center vastu',[j(24),p()], 'NE avoidance overlaps across Jain/Pathi; center avoidance is explicit in Jain.','Check full stair and landing footprints at each level.','Move core within legal, structurally viable zones.',predicate=pred('stairs.avoid_ne_center','eq',True))
add('V17','Prefer clockwise ascent',1,'stairs clockwise landing vastu',[j(24)],'Jain prefers clockwise ascent.','Follow ascending path viewed from above in a right-handed plan; use signed turns, not arrow artwork.','Choose alternate U-stair handedness while preserving landing and structural support.',predicate=pred('stairs.clockwise_ascent','eq',True))
add('V18','Protect entry from direct toilet or stair views',1,'entrance privacy stairs toilet vastu',[j(13),j(24),p(),s(15)],'Avoid entry sightlines directly to toilets or a dominant stair run.','Ray/sightline checks from actual entry aperture into relevant doors and stair; no imaginary partition.','Introduce an accessible foyer/screen or rotate door/core without reducing egress.',predicate=pred('entry.toilet_stair_direct_view','eq',False))
add('V19','Resolve entry pada rules rather than banning south roads',1,'entrance door pada frontage vastu',[j(13)],'Jain supplies side-specific entry divisions, then contradicts itself about S/W residential entries.','Selected frontage, measurement direction and applicable division interval require consultant review. Road frontage is not itself an automatic failure.','Propose alternatives consistent with access; expose disputed interpretation.',conflict='Jain section 13 both permits advantageous S/W positions and later disallows them; no unconditional code predicate.')
add('V20','Ground and overhead tanks have different preferences',1,'tank water underground overhead vastu',[j(26),p(),c(140)],'Selected profile: underground water NE; overhead water SW, subject to engineered support.','Separate tank types, foundation clearance, maintenance and water hygiene; review top-floor mass/eccentricity.','Offer structurally viable options; do not place a heavy tank only to win direction score.',conflict='Pathi names E for underground water in one passage; preserve that as alternative.')
add('V21','Prefer northwest septic location only when feasible',1,'septic drainage northwest vastu',[j(26),p()], 'NW is a directional preference; disposal engineering determines feasibility.','Only if onsite disposal requested/permitted; check size, clearances, outfall, groundwater and access.','Use approved disposal strategy; never reduce sanitary separation to satisfy direction.',predicate=pred('septic.zone','eq','NW'),applies=optional('septic'))

# Vaastu detail tier: still ahead of general aesthetic preferences.
add('V22','Orient cook toward east',2,'kitchen stove facing vastu',[j(16)],'Prefer east-facing cooking; stove location and cook direction are distinct.','Use standing position and cooktop working face in true-north coordinates.','Rotate counter/stove while maintaining working clearances.',predicate=pred('stove.cook_facing','eq','E'))
add('V23','Prefer southeast stove within kitchen',2,'kitchen stove southeast vastu',[j(16)],'Apply SE at room scale, not just house scale.','Room-domain stove footprint; gas/electrical/exhaust safety still governs.','Rearrange appliances without sacrificing ventilation.',predicate=pred('stove.room_zone','eq','SE'))
add('V24','Separate sink and stove; prefer northeast water fixture',2,'kitchen sink water vastu',[j(16),p()], 'Jain separates fire/water fixtures and places sink NE; Pathi places purifier NE.','Check separate footprints, workable preparation surface and selected fixture location. No unsupported numeric separation added.','Adjust kitchen working layout, keeping source of water distinct from heat.',predicate=pred('kitchen.fire_water_layout_satisfied','eq',True))
add('V25','Prefer south or east head direction',2,'bed bedroom sleep direction vastu',[j(18),p()], 'Head S/E is preferred; N is discouraged in these books.','Vector from foot end to head end in world/north coordinates; evaluate each requested bed.','Rotate/reposition beds without blocking doors or reducing clearances.',predicate=pred('beds.all_head_s_or_e','eq',True))
add('V26','Avoid beams directly over beds or work positions',2,'bed beam kitchen dining structure vastu',[j(18),j(16),j(17),p()], 'Prefer occupied resting/work zones without direct overhead beams.','Intersect head/bed/cooking/dining occupied zones with actual beam projections.','Move furniture or coordinate frame; never delete/flatten a structural beam.',predicate=pred('furniture.beam_conflicts','eq',False))
add('V27','Prefer a solid headboard wall',2,'bed window bathroom vastu',[j(18)],'Prefer solid backing; avoid placing bed against bathroom wall or directly before bedroom door.','Model headboard wall, openings, wet-wall adjacency and door sightline separately.','Move bed or bathroom access while keeping furniture fit.',predicate=pred('beds.backing_and_privacy_satisfied','eq',True))
add('V28','Prefer northwest guest bedroom',2,'guest bedroom northwest vastu',[j(21),p(),c(140)],'NW is a recurring guest-room preference.','Apply only to actual guest room, not automatically every secondary bedroom.','Try NW after essential cores; document competing wet-room demand.',predicate=pred('guest.zone','eq','NW'),applies=optional('guest'))
add('V29','Select children bedroom tradition explicitly',2,'children bedroom study vastu',[j(20),p()], 'Jain favors W then N/E; Pathi recommends NE for children/older people.','Use household needs and explicit profile; prioritize accessibility for any resident.','Record chosen room rule; do not infer age/gender hierarchy.',conflict='Different sources assign different directions; no blanket NE-bedroom ban for every room.')
add('V30','Orient study work toward east or north',2,'study desk children vastu',[p()], 'Prefer E/N-facing study activity.','Use chair/desk working-face vector rather than room label.','Rotate desk with daylight/glare and clearance checks.',predicate=pred('study.facing','in',['E','N']),applies=optional('study'))
add('V31','Keep dining linked to kitchen on the same floor',2,'dining kitchen adjacency vastu',[j(17),p()], 'Jain specifies same floor; Pathi emphasizes proximity.','Shortest usable route and floor IDs; no access through private bedrooms.','Relocate dining within public realm.',predicate=pred('dining.kitchen_same_floor_accessible','eq',True))
add('V32','Treat dining direction as a profile choice',2,'dining west east south vastu',[j(17),p()], 'Jain favors W then N/E; Pathi suggests S/E near kitchen.','Prefer practical adjacency and selected tradition; do not require incompatible locations.','Show ranked alternatives with source conflict.',conflict='Dining compass preferences differ; adjacency is the reliable shared design relation.')
add('V33','Prefer open north/east-facing living spaces where lawful',2,'living windows north east vastu',[j(15),p()], 'Jain favors E/N/NW; Pathi favors NE/NW and sometimes center.','Score room exposure and habitable light, not a compass label alone.','Choose usable daylight and legal opening placement.',predicate=pred('living.selected_profile_location_satisfied','eq',True))
add('V34','Keep prayer orientation distinct from room location',2,'puja idol facing vastu',[j(14)],'Jain recommends worshipper facing E, idol facing W.','Model idol front, worshipper location and actual access in the room.','Rotate arrangement without relocating room unnecessarily.',predicate=pred('puja.worshipper_facing','eq','E'),applies=optional('puja'))
add('V35','Orient WC user north or south in selected profile',2,'wc toilet orientation vastu',[j(19)],'Jain discourages E/W-facing WC use.','Use seated-person direction, not cistern/front-wall label; preserve usable bathroom fit.','Rotate fixture and recheck soil connection/clearances.',predicate=pred('wc.all_user_facing_n_s','eq',True))
add('V36','Prefer south/west heavy storage',2,'closet storage furniture vastu',[j(18),j(15),p()], 'Locate substantial wardrobes/storage toward S/W/SW in the relevant room.','Test actual closet footprint, usable access, door swing and room-scale orientation.','Reposition built-in storage without sacrificing structure/egress.',predicate=pred('storage.selected_profile_location_satisfied','eq',True))
add('V37','Keep legal daylight openings toward north/east when possible',2,'windows opening daylight vastu',[j(12),p()], 'N/E openings are favored by these books.','Compare usable/exposed openings by orientation; statutory light/ventilation and boundary permission remain gates.','Shift rooms or court arrangement; do not draw illegal boundary windows.',predicate=pred('openings.north_east_preference_satisfied','eq',True))
add('V38','Prefer a legible larger main entrance',2,'door entrance width vastu',[j(13),j(12)],'Main entry is emphasized as larger than other domestic doors.','Compare actual clear openings; do not reduce other required opening widths.','Increase entry where feasible and desired.',predicate=pred('entry.emphasis_satisfied','eq',True))
add('V39','Door swing preferences cannot override exit/access requirements',2,'door swing threshold vastu',[j(13),p(),ref('nbc206-2024',12)],'Books favor inward/clockwise entry; thresholds are also mentioned.','Separate preference from required egress swing/accessibility and landing clearance; coordinate sign convention.','Use safe compliant swing; record departure rather than adding a hazardous threshold.')
add('V40','Odd stair count is an optional secondary detail',2,'stairs riser count vastu',[j(24),p()], 'Books prefer odd steps but do not establish an engineering riser-count convention.','Before enabling, define whether count is risers per flight or total rise; keep risers uniform and within legal limits.','Choose a different valid count only if safe; never add a tiny step.',conflict='Counting convention unspecified. Default is manual advisory, not executable.')
add('V41','Prefer orthogonal landing stairs',2,'stairs half turn landing vastu',[j(24)],'Jain favors square/rectangular right-angle arrangements over circular/spiral. Owner separately selects half-turn with landing as Nepal default.','Check actual stair type; straight/quarter-turn alternatives can be compliant and user-selected.','Start with U-stair and landing; preserve legal geometry and structure.',predicate=pred('stairs.orthogonal_landing_type','eq',True))
add('V42','Parking location is not a vehicle-access calculation',2,'parking bike car garage vastu',[j(23)],'Jain favors SE/NW garage and discourages NE.','Only score after maneuvering, gates, walking paths and area accounting pass.','Choose feasible parking first, then best directional fit.',predicate=pred('parking.selected_profile_location_satisfied','eq',True),applies=optional('parking'))
add('V43','Landscape and drainage preferences need site engineering',2,'slope drainage landscape northeast vastu',[j(25),p(),c(149)],'Sources favor lower/open N/E/NE; this is a preference, not authorization to direct water there.','Check actual lawful outfall, falls, neighboring plots and accessibility.','Keep engineered drainage; acknowledge directional mismatch rather than flood another site.')
add('V44','Keep worship space dedicated and calm',2,'puja privacy clutter vastu',[j(14),s(18)],'Prefer a distinct, uncluttered prayer zone separate from bedroom/kitchen functions.','Check use and furniture conflicts; dedicated alcove only by explicit household choice.','Reserve appropriate floor area early.',predicate=pred('puja.dedicated_uncluttered','eq',True),applies=optional('puja'))
add('V45','Use color as a reversible preference',2,'color facade interior vastu',[j(14),j(15),j(16),j(18),j(24)],'Room-specific light/warm palettes are discussed; retain owner choice and local multicolor facade preference.','Apply colors to actual surfaces after geometry; do not claim health or wealth effects.','Offer palette variants without disguising structural/window changes.')
add('V46','Do not use symbolic remedies as geometric repairs',1,'remedy mirror vastu safety',[j(24),j(38)],'Jain describes symbolic mirror/remedy practices. These do not change stairs, structure or plan geometry.','Keep any user-requested ritual item separate from geometry compliance.','Report original geometric preference failure; never erase it with a remedy.',predicate=pred('vastu.no_symbolic_compliance_override','eq',True))

# Architectural synthesis and provenance controls.
add('A01','Design from household activity and usable furniture',3,'furniture activity privacy architecture',[s(12),s(18)],'Svoboda emphasizes intention and practical use; apply the earlier Keystone activity-first design approach.','Prove bed/work/seating/fixture clearances and useful paths.','Rework room geometry before decoration.',predicate=pred('architecture.activity_fit','eq',True))
add('A02','Preserve a readable entrance-to-private-space sequence',3,'privacy circulation entrance architecture',[s(15)],'Entry experience and what is visible affect spatial organization.','Guest routes to public spaces should not require crossing private bedrooms.','Recluster public/private rooms; minimize wasted corridors.',predicate=pred('architecture.privacy_routes','eq',True))
add('A03','Interpret the tradition as a whole, not disconnected compass slogans',3,'tradition mandala architecture',[c(18),c(136),c(137),s(18)],'Chakrabarti distinguishes integrated traditional systems from selective contemporary prescriptions.','Record selected tradition, mandala interpretation, household intent and source conflicts.','Avoid mixing conflicting rules while calling them universal.')
add('A04','Use practice profiles for spatial inspiration only',3,'courtyard light architecture case study',[ref('architecture-kathpalia',1)],'The uploaded magazine PDF profiles architecture practices; its title is not proof of a Vaastu rule system.','Extract case-specific spatial lessons only after inspecting relevant project pages.','Do not invent directional doctrine from an architectural firm name.')
add('A05','Treat the illustrated plans as references, not Nepal-approved templates',3,'plans examples dimensions architecture',[p()], 'Pathi supplies plan images and a general principles section, not Nepal permit or RC certification.','Check each selected image scale, openings, stairs, structure and local applicability.','Rebuild and validate an adapted plan instead of tracing it as approved.')

POLICY={
 'version':'np-vastu-first-0.1',
 'priority_order':['0 mandatory legal/safety feasibility and confirmed engineering','1 Vaastu core spatial organization','2 Vaastu fixture/detail preferences','3 other architectural/presentation preferences'],
 'selection':'Lexicographic preference ranking only after complete applicable critical checks. User-required program/essential preferences are hard constraints; conflicts require explicit resolution.',
 'default_tradition':'Jain-led spatial profile with corroboration and explicit Pathi/Chakrabarti/Svoboda disagreements; not a consensus or professional approval.',
 'unknown_policy':'Missing applicability, measurements, source interpretation or local adoption never pass.',
 'claims':'Directional beliefs are treated as cultural preferences. No medical, financial, seismic or supernatural outcome is asserted.',
 'scope':'Local retrieval and fact evaluation only; not connected to production plan generation.'}

def build():
    manifest={m['id']:m for m in json.loads((ROOT/'manifest.json').read_text(encoding='utf-8'))}
    for rule in RULES:
        for source in rule['sources']:
            source['sha256']=manifest[source['source_id']]['sha256']
    out={'schema_version':1,'policy':POLICY,'rules':RULES}
    (ROOT/'rules.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    lines=['# Source-linked house-design rule catalog','',f'{len(RULES)} curated rules. Highest design preference: Vaastu. Mandatory legal/safety constraints remain gates. Source facts and Keystone operationalization are distinguished in each rule. No professional approval is claimed.','', 'Read [the synthesis](DESIGN-PRINCIPLES.md) and [integration contract](INTEGRATION.md) before using these rules.','']
    for r in RULES:
        links=', '.join(f'[{x["source_id"]} {x["locator"]}](sources/{x["source_id"]}.md#{x["locator"]})' for x in r['sources'])
        lines += [f'## {r["id"]} — {r["title"]}', '',f'Priority tier: **{r["tier"]}**. Tags: '+', '.join(r['tags']), '',r['principle'],'',f'**Measure:** {r["measurement"]}', '',f'**Repair:** {r["repair"]}', '',f'**Interpretation/conflict:** {r["conflict"]}', '',f'**Sources:** {links}', '']
        if r['predicate']: lines += ['**Executable fact predicate:** `'+json.dumps(r['predicate'],ensure_ascii=False)+'`.','']
        if r['applies_when']: lines += ['**Applicability:** `'+json.dumps(r['applies_when'])+'`.','']
    (ROOT/'RULE-CATALOG.md').write_text('\n'.join(lines),encoding='utf-8')
    print(f'Built {len(RULES)} rules')

if __name__=='__main__':build()
